version: '3'
services:
  nginx-container:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
  python:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
